# Docker Compose Configuration Contract
# Validates docker-compose.yml structure and requirements

version: '3.8'
services:
  neo4j:
    required: true
    image_pattern: "neo4j:5\\.26\\.\\d+"
    ports:
      - required: ["7474:7474", "7687:7687"]
    environment:
      - required: ["NEO4J_AUTH", "NEO4J_server_memory_heap_initial__size"]
    volumes:
      - required: ["neo4j_data:/data", "neo4j_logs:/logs"]
    healthcheck:
      required: true
      test_pattern: ".*localhost:7474.*"
      interval_max: 30s
      retries_min: 3

  graphiti-mcp:
    required: true
    build_context: "."
    dockerfile: "Dockerfile"
    depends_on:
      - service: "neo4j"
        condition: "service_healthy"
    environment:
      - required: ["NEO4J_URI", "OPENAI_API_KEY", "MODEL_NAME"]
    ports:
      - required: ["8000:8000"]
    command_pattern: ".*sse.*"

volumes:
  neo4j_data:
    required: true
    driver: "local"
  neo4j_logs:
    required: true
    driver: "local"

# Validation Rules
validation_rules:
  - no_conflicting_ports: ["7474", "7687", "8000"]
  - required_env_file: ".env"
  - dockerfile_exists: true
  - volume_persistence: true