services:
  neo4j:
    image: neo4j:5.26.0-enterprise
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-demodemo}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*,bloom.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*,bloom.*
    volumes:
      - ~/neo4j-data/graphiti/data:/data
      - ~/neo4j-data/graphiti/logs:/logs
      - ~/neo4j-data/graphiti/import:/var/lib/neo4j/import
      - ~/neo4j-data/graphiti/plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474 || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 3s

  graphiti-mcp:
    build:
      context: .
    env_file:
      - path: .env
        required: false # Makes the file optional. Default value is 'true'
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-demodemo}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - PATH=/root/.local/bin:${PATH}
      - SEMAPHORE_LIMIT=${SEMAPHORE_LIMIT:-10}
    ports:
      - "0.0.0.0:8000:8000" # Expose the MCP server via HTTP for SSE transport - accessible externally
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]

volumes:
  neo4j_data:
  neo4j_logs:
